### PR TITLE
CSCFAIRMETA-335: Add information text to "permission required" access type.

### PR DESCRIPTION
**Pull request by tahme**

### CODE REVIEW

**Comment by MattiasLevlin** [comment]
This shouldn't be reviewed & merged to next yet. Cumulative fixes need to be pushed to next and release first. So, merge can be done after Qvain's production has been updated.

**Review by jppiiroinen — APPROVED** [review]

**Review by ShreyasDeshpande — APPROVED** [review]
Code looks straight forward. Approving the pull request.

**Comment by MattiasLevlin** [comment]
> Code looks straight forward. Approving the pull request.

Good, but verified again after internal discussion that the pull request shouldn't be merged yet.

**Comment by MattiasLevlin** [comment]
This can be merged now.

**Pull request merged**
